const List<String> kNotesBranches = [
  'CSE',
  'ISE',
  'AIML',
  'ECE',
  'EEE',
  'CIVIL',
  'MECH',
];

const List<String> kNotesSemesters = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
];

final Map<String, List<String>> kNotesSubjectsByBranchSem = {
  'CSE-1': [
    'Mathematical Foundations For CSE Stream-1',
    'Applied Physics For CSE Stream',
    'Principle of Programming in C',
    'Introduction to Python Programming',
    'Introduction to Electrical Engineering',
    'Introduction to Mechanical Engineering',
    'Introduction to Civil Engineering',
    'Communication English',
    'Balake Kannada',
    'Samskrutika Kannada',
  ],
  'CSE-2': [
    'Mathematical Foundations For CSE Stream-2',
    'Applied Physics For CSE Stream',
    'Principle of Programming in C',
    'Introduction to Python Programming',
    'Introduction to Electrical Engineering',
    'Introduction to Mechanical Engineering',
    'Introduction to Civil Engineering',
    'Balake Kannada',
    'Samskrutika Kannada',
    'Professional English Writing Skills',
  ],
  'ISE-1': [
    'Mathematical Foundations For CSE Stream-1',
    'Applied Physics For CSE Stream',
    'Principle of Programming in C',
    'Introduction to Python Programming',
    'Introduction to Electrical Engineering',
    'Introduction to Mechanical Engineering',
    'Introduction to Civil Engineering',
    'Communication English',
    'Balake Kannada',
    'Samskrutika Kannada',
  ],
  'ISE-2': [
    'Mathematical Foundations For CSE Stream-2',
    'Applied Physics For CSE Stream',
    'Principle of Programming in C',
    'Introduction to Python Programming',
    'Introduction to Electrical Engineering',
    'Introduction to Mechanical Engineering',
    'Introduction to Civil Engineering',
    'Balake Kannada',
    'Samskrutika Kannada',
    'Professional English Writing Skills',
  ],
  'ECE-1': [
    'Mathematical Foundations For ECE Stream-1',
    'Applied Physics For ECE Stream',
    'Basic Electronics',
    'Introduction to Python Programming',
    'Introduction to Electrical Engineering',
    'Introduction to Mechanical Engineering',
    'Introduction to Civil Engineering',
    'Communication English',
    'Balake Kannada',
    'Samskrutika Kannada',
  ],
  'ECE-2': [
    'Mathematical Foundations For ECE Stream-2',
    'Applied Physics For ECE Stream',
    'Basic Electronics',
    'Introduction to Python Programming',
    'Introduction to Electrical Engineering',
    'Introduction to Mechanical Engineering',
    'Introduction to Civil Engineering',
    'Balake Kannada',
    'Samskrutika Kannada',
    'Professional English Writing Skills',
  ],
  'EEE-1': [
    'Mathematical Foundations For ECE Stream-1',
    'Applied Physics For ECE Stream',
    'Basic Electronics',
    'Introduction to Python Programming',
    'Introduction to Electrical Engineering',
    'Introduction to Mechanical Engineering',
    'Introduction to Civil Engineering',
    'Communication English',
    'Balake Kannada',
    'Samskrutika Kannada',
  ],
  'EEE-2': [
    'Mathematical Foundations For ECE Stream-2',
    'Applied Physics For ECE Stream',
    'Basic Electronics',
    'Introduction to Python Programming',
    'Introduction to Electrical Engineering',
    'Introduction to Mechanical Engineering',
    'Introduction to Civil Engineering',
    'Balake Kannada',
    'Samskrutika Kannada',
    'Professional English Writing Skills',
  ],
  'CIVIL-1': [
    'Mathematical Foundations For Mech Stream-1',
    'Applied Physics For Mech Stream',
    'Principle of Programming in C',
    'Introduction to Python Programming',
    'Introduction to Electrical Engineering',
    'Introduction to Mechanical Engineering',
    'Introduction to Civil Engineering',
    'Communication English',
    'Balake Kannada',
    'Samskrutika Kannada',
  ],
  'CIVIL-2': [
    'Mathematical Foundations For Mech Stream-2',
    'Applied Physics For Mech Stream',
    'Principle of Programming in C',
    'Introduction to Python Programming',
    'Introduction to Electrical Engineering',
    'Introduction to Mechanical Engineering',
    'Introduction to Civil Engineering',
    'Balake Kannada',
    'Samskrutika Kannada',
    'Professional English Writing Skills',
  ],
  'MECH-1': [
    'Mathematical Foundations For Mech Stream-1',
    'Applied Physics For Mech Stream',
    'Principle of Programming in C',
    'Introduction to Python Programming',
    'Introduction to Electrical Engineering',
    'Introduction to Mechanical Engineering',
    'Introduction to Civil Engineering',
    'Communication English',
    'Balake Kannada',
    'Samskrutika Kannada',
  ],
  'MECH-2': [
    'Mathematical Foundations For Mech Stream-2',
    'Applied Physics For Mech Stream',
    'Principle of Programming in C',
    'Introduction to Python Programming',
    'Introduction to Electrical Engineering',
    'Introduction to Mechanical Engineering',
    'Introduction to Civil Engineering',
    'Balake Kannada',
    'Samskrutika Kannada',
    'Professional English Writing Skills',
  ],
  'AIML-1': [
    'Mathematical Foundations For CSE Stream-1',
    'Applied Physics For CSE Stream',
    'Principle of Programming in C',
    'Introduction to Python Programming',
    'Introduction to Electrical Engineering',
    'Introduction to Mechanical Engineering',
    'Introduction to Civil Engineering',
    'Communication English',
    'Balake Kannada',
    'Samskrutika Kannada',
  ],
  'AIML-2': [
    'Mathematical Foundations For CSE Stream-2',
    'Applied Physics For CSE Stream',
    'Principle of Programming in C',
    'Introduction to Python Programming',
    'Introduction to Electrical Engineering',
    'Introduction to Mechanical Engineering',
    'Introduction to Civil Engineering',
    'Balake Kannada',
    'Samskrutika Kannada',
    'Professional English Writing Skills',
  ],
  'CSE-3': [
    'Computer Organisation & Architecture',
    'Statistics and Discrete Mathematics',
    'Object Oriented Java Programming',
    'Logic Design',
    'Database Management System',
    'Data Structures',
  ],
  'CSE-4': [
    'Web Technologies',
    'Operating Systems',
    'Computer Networks',
    'Software Engineering',
    'Analysis of Algorithms',
    'Compiler Design',
  ],
  'CSE-5': [
    'Database Systems Advanced',
    'Artificial Intelligence',
    'Information Security',
    'Machine Learning',
    'Distributed Computing',
    'Cloud Computing',
  ],
  'CSE-6': [
    'Mobile Application Development',
    'Big Data Analytics',
    'Internet of Things',
    'Blockchain Technology',
    'Cyber Security',
    'Advanced Algorithms',
  ],
  'CSE-7': [
    'Project Work - Part 1',
    'Elective 1',
    'Elective 2',
    'Elective 3',
    'Seminar',
    'Industrial Training',
  ],
  'CSE-8': [
    'Project Work - Part 2',
    'Elective 4',
    'Elective 5',
    'Internship',
    'Final Year Project',
    'Industry Collaboration',
  ],
  'ISE-3': [
    'Computer Organisation & Architecture',
    'Statistics and Discrete Mathematics',
    'Object Oriented Java Programming',
    'Logic Design',
    'Database Management System',
    'Data Structures',
  ],
  'ISE-4': [
    'Web Technologies',
    'Operating Systems',
    'Computer Networks',
    'Software Engineering',
    'Analysis of Algorithms',
    'Compiler Design',
  ],
  'ISE-5': [
    'Database Systems Advanced',
    'Software Quality & Testing',
    'Information Security',
    'Mobile Development',
    'DevOps & CI-CD',
    'Microservices',
  ],
  'ISE-6': [
    'Enterprise Software Architecture',
    'Cloud Technologies',
    'Agile Methodologies',
    'Software Project Management',
    'Advanced Networking',
    'System Design',
  ],
  'ISE-7': [
    'Project Work - Part 1',
    'Elective 1',
    'Elective 2',
    'Elective 3',
    'Seminar',
    'Industrial Training',
  ],
  'ISE-8': [
    'Project Work - Part 2',
    'Elective 4',
    'Elective 5',
    'Internship',
    'Final Year Project',
    'Industry Collaboration',
  ],
  'ECE-3': [
    'Signals and Systems',
    'Electromagnetic Theory',
    'Digital Signal Processing',
    'Control Systems',
    'Power Electronics',
    'Microprocessors',
  ],
  'ECE-4': [
    'Communication Systems',
    'RF and Microwave Engineering',
    'VLSI Design',
    'Embedded Systems',
    'Power Systems',
    'High Frequency Circuits',
  ],
  'ECE-5': [
    'Optical Communications',
    'Wireless Communications',
    'Advanced VLSI',
    'IoT and Sensors',
    'Power Conversion',
    'Advanced Control Systems',
  ],
  'ECE-6': [
    '5G Technology',
    'Radar and Navigation',
    'Biomedical Devices',
    'Renewable Energy Systems',
    'Advanced Electromagnetics',
    'System on Chip Design',
  ],
  'ECE-7': [
    'Project Work - Part 1',
    'Elective 1',
    'Elective 2',
    'Elective 3',
    'Seminar',
    'Industrial Training',
  ],
  'ECE-8': [
    'Project Work - Part 2',
    'Elective 4',
    'Elective 5',
    'Internship',
    'Final Year Project',
    'Industry Collaboration',
  ],
  'EEE-3': [
    'Circuit Theory',
    'Electromagnetic Fields',
    'Electrical Machines',
    'Power Systems',
    'Switchgear & Protection',
    'Electrical Installation Technology',
  ],
  'EEE-4': [
    'Power Generation',
    'Power Transmission & Distribution',
    'High Voltage Engineering',
    'Renewable Energy Sources',
    'Power Electronics',
    'Electrical Drives',
  ],
  'EEE-5': [
    'Advanced Power Systems',
    'Smart Grid Technology',
    'Energy Management',
    'HVDC Technology',
    'Industrial Power Systems',
    'Electrical Testing & Commissioning',
  ],
  'EEE-6': [
    'Power Quality & Harmonics',
    'Microgrid Technology',
    'Demand Side Management',
    'Underground Cabling',
    'Substations Design',
    'Power System Operation & Control',
  ],
  'EEE-7': [
    'Project Work - Part 1',
    'Elective 1',
    'Elective 2',
    'Elective 3',
    'Seminar',
    'Industrial Training',
  ],
  'EEE-8': [
    'Project Work - Part 2',
    'Elective 4',
    'Elective 5',
    'Internship',
    'Final Year Project',
    'Industry Collaboration',
  ],
  'CIVIL-3': [
    'Strength of Materials',
    'Structural Analysis',
    'Fluid Mechanics',
    'Surveying',
    'Building Materials',
    'Soil Mechanics',
  ],
  'CIVIL-4': [
    'Design of Concrete Structures',
    'Steel Structures Design',
    'Hydraulics and Hydraulic Machines',
    'Transportation Engineering',
    'Geotechnical Engineering',
    'Building Design',
  ],
  'CIVIL-5': [
    'Advanced Structural Analysis',
    'Prestressed Concrete',
    'Water Resources Engineering',
    'Environmental Engineering',
    'Foundation Engineering',
    'Advanced Soil Mechanics',
  ],
  'CIVIL-6': [
    'Bridge Engineering',
    'Tunneling & Underground Construction',
    'Urban Planning & Development',
    'Coastal Engineering',
    'Earthquake Engineering',
    'Advanced Water Resources',
  ],
  'CIVIL-7': [
    'Project Work - Part 1',
    'Elective 1',
    'Elective 2',
    'Elective 3',
    'Seminar',
    'Site Supervision & Internship',
  ],
  'CIVIL-8': [
    'Project Work - Part 2',
    'Elective 4',
    'Elective 5',
    'Project Internship',
    'Final Year Project',
    'Professional Practice',
  ],
  'MECH-3': [
    'Heat Transfer',
    'Mechanical Design',
    'Production Engineering',
    'Thermal Engineering',
    'Mechanical Vibrations',
    'Automobile Engineering',
  ],
  'MECH-4': [
    'Internal Combustion Engines',
    'Refrigeration & Air Conditioning',
    'Power Plant Engineering',
    'Machine Tools & Operations',
    'Mechanical Measurements & Control',
    'CAD/CAM',
  ],
  'MECH-5': [
    'Advanced Heat Transfer',
    'Compressors & Turbines',
    'Energy & Environmental Engineering',
    'Advanced Manufacturing',
    'Robotics & Automation',
    'Finite Element Analysis',
  ],
  'MECH-6': [
    'Advanced Thermal Systems',
    'System Design & Optimization',
    'Industrial Management',
    'Computational Fluid Dynamics',
    'Advanced Materials & Processes',
    'Solar Energy Engineering',
  ],
  'MECH-7': [
    'Project Work - Part 1',
    'Elective 1',
    'Elective 2',
    'Elective 3',
    'Seminar',
    'Industrial Training',
  ],
  'MECH-8': [
    'Project Work - Part 2',
    'Elective 4',
    'Elective 5',
    'Internship',
    'Final Year Project',
    'Industry Collaboration',
  ],
  'AIML-3': [
    'Linear Algebra & Calculus',
    'Probability & Statistics',
    'Computer Organisation & Architecture',
    'Database Management System',
    'Data Structures',
    'Discrete Mathematics',
  ],
  'AIML-4': [
    'Machine Learning Fundamentals',
    'Data Mining',
    'Web Technologies',
    'Operating Systems',
    'Object Oriented Programming',
    'Analysis of Algorithms',
  ],
  'AIML-5': [
    'Advanced Machine Learning',
    'Deep Learning',
    'Natural Language Processing',
    'Computer Vision',
    'Reinforcement Learning',
    'Big Data Analytics',
  ],
  'AIML-6': [
    'Optimization Techniques',
    'Time Series Analysis',
    'Recommendation Systems',
    'Explainable AI',
    'Edge AI & IoT',
    'AI Ethics & Responsible AI',
  ],
  'AIML-7': [
    'Project Work - Part 1',
    'Elective 1',
    'Elective 2',
    'Elective 3',
    'Seminar',
    'Industrial Training',
  ],
  'AIML-8': [
    'Project Work - Part 2',
    'Elective 4',
    'Elective 5',
    'Internship',
    'Final Year Project',
    'Industry Collaboration',
  ],
};

List<String> getNotesSubjects(String? branch, String? semester) {
  if (branch == null || semester == null) return [];
  return kNotesSubjectsByBranchSem['$branch-$semester'] ?? [];
}
